include:
- file: /r4.3/gitlab-base.yml
  project: QubesOS/qubes-continuous-integration
  ref: $CI_BRANCH_REF
- file: /r4.3/gitlab-host.yml
  project: QubesOS/qubes-continuous-integration
  ref: $CI_BRANCH_REF
- file: /r4.3/gitlab-vm.yml
  project: QubesOS/qubes-continuous-integration
  ref: $CI_BRANCH_REF
- file: /r4.3/gitlab-host-vm-openqa.yml
  project: QubesOS/qubes-continuous-integration
  ref: $CI_BRANCH_REF
variables:
  CI_INSTALL_EXCLUDE: pulseaudio-qubes pulseaudio-qubes-dbgsym qubes-vm-pulseaudio
  CI_INSTALL_EXCLUDE_DOM0: pulseaudio-qubes qubes-gui-agent
